version: "3.6"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    restart: unless-stopped
  web:
    image: ghcr.io/dlgeraghty/abd_web:1.0
    volumes:
      - ./src:/var/www/html
    ports: 
      - "8090:80"

